/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package distributedlogservice;

public class DistributedLogServiceLauncher {

    public static void main(String[] args) {
        DistributedLogService service = new DistributedLogService();
        service.launch();
    }
}
