/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package management_service;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        ManagementServiceApp classUnderTest = new ManagementServiceApp();
    }
}
