/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package user_service;

import io.vertx.core.Vertx;

public class UserServiceApp {

    public static void main(String[] args) {
        UserServiceApp app = new UserServiceApp();
        app.run();
    }

    private void run() {
        Vertx vertx = Vertx.vertx();
        vertx.deployVerticle(new UserServiceVerticle());
    }
}
