services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    healthcheck:
      test: |
        host=`hostname --ip-address || echo '127.0.0.1'`;
        mongo --quiet $${host}/test --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)' && echo 0 || echo 1
      interval: 5s

  mongodb-seed:
    image: mongo
    environment:
      - import=true
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./import:/databases:ro
    command: /bin/bash -c "/databases/init.sh"

  mongo-express:
    depends_on:
      mongo:
        condition: service_healthy
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/