/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package user_service;

import org.junit.Test;
import static org.junit.Assert.*;

public class UserServiceAppTest {
    @Test public void appHasAGreeting() {
        UserServiceApp classUnderTest = new UserServiceApp();
    }
}
