/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package forwarding_service;

import forwarding_service.routes.DefaultRoute;
import forwarding_service.routes.ManagementServiceRoute;
import forwarding_service.routes.RideServiceRoute;
import forwarding_service.routes.UserRoute;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import io.github.resilience4j.circuitbreaker.CircuitBreaker;
import org.springframework.cloud.gateway.route.RouteLocator;
import org.springframework.cloud.gateway.route.builder.RouteLocatorBuilder;
import org.springframework.context.annotation.Bean;

@SpringBootApplication
public class ApiGateway {

    private final CircuitBreaker circuitBreaker;

    public ApiGateway(CircuitBreaker circuitBreaker) {
        this.circuitBreaker = circuitBreaker;
    }

    @Bean
    public RouteLocator defaultRoute(RouteLocatorBuilder builder) {
        return new DefaultRoute(circuitBreaker).route(builder);
    }

    @Bean
    public RouteLocator userRoute(RouteLocatorBuilder builder) {
        return new UserRoute(circuitBreaker).route(builder);
    }

    @Bean
    public RouteLocator managementServiceRoute(RouteLocatorBuilder builder) {
        return new ManagementServiceRoute(circuitBreaker).route(builder);
    }

    @Bean
    public RouteLocator rideServiceRoute(RouteLocatorBuilder builder) {
        return new RideServiceRoute(circuitBreaker).route(builder);
    }


    public static void main(String[] args) {
        SpringApplication.run(ApiGateway.class, args);
    }
}
