/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package distributedlogservice;

import org.junit.Test;

public class AppTest {
    @Test public void appHasAGreeting() {
        DistributedLogServiceLauncher classUnderTest = new DistributedLogServiceLauncher();
    }
}
